# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsimage',
            old_name='caption',
            new_name='aff_link',
        ),
    ]
