# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ads', '0002_auto_20170629_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='background_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='button_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
